### ISSUE TITLE
Update login endpoint

### ISSUE THREAD

**Issue by romanstrobl** [lime-company/powerauth-enrollment-server#3]
The endpoint should be only accessible via `POST` method. The expected OK response is empty. The resource ID is `/pa/login`. Supported signature types are `POSSESSION_KNOWLEDGE` and `POSSESSION_BIOMETRY`.

**Comment by petrdvorak** [comment]
We can completely remove this endpoint, since:

- This login endpoint is supposed to be implemented on the application API gateway (not by us), and...
- We already have (undocumented so far) `/pa/signature/validate` endpoint in PA Standard RESTful API that basically does the same thing...

**Comment by romanstrobl** [comment]
Ok, sorry, my misunderstanding. I will remove the endpoint.

I added tasks for all the other changes, can you please check that all of them make sense?

https://github.com/lime-company/powerauth-enrollment-server/issues

**Comment by petrdvorak** [comment]
yes, I will have a look
