### ISSUE TITLE
Implement service for communication with credentials verification endpoint

### ISSUE THREAD

**Issue by romanstrobl** [lime-company/powerauth-enrollment-server#5]
The credentials verification endpoint URL should be configurable.

Request:
```
POST /user/login
{     
   "username": "johndoe",     
   "password": "s3cr3t++" 
}
```

Response:
```
200 - OK
 {     
   "userId": "USER_1234567890" 
}
401 - Unauthorized
{ }
```

**Comment by petrdvorak** [comment]
Please note that this service is not supposed to be implemented by us. We only need a mock service for testing, and it should probably be in another WAR / application.

**Comment by petrdvorak** [comment]
(Of course, we need to have a client for this service, which is what this task is really about.)
